- name: ensure photoprism folder exists
  file:
    path: "{{ DOCKER.host_path }}/photoprism"
    recurse: yes
    state: directory

- name: Start container Photoprism
  community.docker.docker_container:
    name: photoprism
    image: "photoprism/photoprism:latest"
    state: started
    recreate: no
    pull: yes
    restart_policy: always
    env: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_ADMIN_PASSWORD: "{{ admin_password }}"     # Initial admin password: PLEASE CHANGE!
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "true"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_SITE_URL: "{{ traefik.url }}"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "{{ site_title }}"
      PHOTOPRISM_SITE_CAPTION: "{{ site_caption }}"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: "2342"
      PHOTOPRISM_SETTINGS_HIDDEN: "false"            # Users can not view or change settings
      PHOTOPRISM_DATABASE_DRIVER: "mysql"           # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DSN: "{{ SQL.user }}:{{ SQL.password }}@tcp({{ SQL.host }}:{{ SQL.port }})/{{ SQL.db }}?charset=utf8mb4,utf8&parseTime=true"
      PHOTOPRISM_SIDECAR_JSON: "true"                # Automatically create JSON sidecar files using Exiftool
      PHOTOPRISM_SIDECAR_YAML: "false"                # Automatically backup metadata to YAML sidecar files
      PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: "1024"                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      PHOTOPRISM_THUMB_SIZE_UNCACHED: "7680"           # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: "7680"                     # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: "80"                    # Set to 95 for high-quality thumbnails (25-100)
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use darktable presets (disables concurrent raw to jpeg conversion)
      PHOTOPRISM_ORIGINALS_PATH: "/data/"
    volumes:
      - "{{ DOCKER.host_path }}/photoprism:/photoprism/storage"
      - "{{ photo_path }}:/data:ro"
    networks:
      - name: "{{ DOCKER.net.traefik }}"
      - name: "{{ DOCKER.net.dbms }}"
    purge_networks: yes
    security_opts:
      - seccomp:unconfined
      - apparmor:unconfined
    labels:
      traefik.frontend.rule: "Host: {{ traefik.url }}"
      traefik.port: "2342"
      traefik.enable: "true"