- name: "Start redis"
  community.docker.docker_container:
    name: redis
    image: redis:alpine
    pull: true
    state: started
    recreate: yes
    restart_policy: always
    published_ports:
      - "6379:6379"
    networks:
      - name: "{{ DOCKER.net.dbms }}"
    purge_networks: yes