- name: "Combine defaults and watchtower_config_override variables"
  set_fact:
    wtw_combined_env: "{{ watchtower_env | combine(watchtower_config_override) }}"


- community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    state: started
    recreate: yes
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_NOTIFICATIONS: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATIONS | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_FROM | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_TO | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_SERVER | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG | default(omit) }}"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: "{{ wtw_combined_env.WATCHTOWER_NOTIFICATION_EMAIL_DELAY | default(omit) }}"
      WATCHTOWER_NO_STARTUP_MESSAGE: "{{ wtw_combined_env.WATCHTOWER_NO_STARTUP_MESSAGE | default(omit) }}"
      WATCHTOWER_INCLUDE_STOPPED: "{{ wtw_combined_env.WATCHTOWER_INCLUDE_STOPPED | default(omit) }}"
      WATCHTOWER_CLEANUP: "{{ wtw_combined_env.WATCHTOWER_CLEANUP | default(omit) }}"
      WATCHTOWER_SCHEDULE: "{{ wtw_combined_env.WATCHTOWER_SCHEDULE | default(omit) }}"
      WATCHTOWER_DEBUG: "{{ wtw_combined_env.WATCHTOWER_DEBUG | default(omit) }}"
