- name: "Start portainer agent"
  community.docker.docker_container:
    name: portainer
    image: portainer/agent
    pull: true
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "9001:9001"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    purge_networks: no