- docker_volume:
    name: caddy-volume
    state: present
    recreate: never

- name: "Copy Caddy config"
  template:
    src: Caddyfile.j2
    dest: "{{ DOCKER.host_path }}/Caddyfile"

- name: "Create caddy external network"
  docker_network:
    name: "{{ DOCKER.net.caddy }}"

- name: "Start Caddy"
  community.docker.docker_container:
    name: caddy
    image: abiosoft/caddy:no-stats
    pull: true
    state: started
    restart_policy: always
    recreate: no
    container_default_behavior: "compatibility"
    env:
      ACME_AGREE: "true"
      AWS_ACCESS_KEY_ID: "{{ AWS.access_key | default(omit) }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS.secret | default(omit) }}"
    ports:
      - "443:443"
    volumes:
      - "{{ DOCKER.host_path }}/Caddyfile:/etc/Caddyfile"
      - /etc/ssl/crt/ca.pem:/etc/ca.crt
      - caddy-volume:/root/.caddy
    network_mode: "{{ DOCKER.net.caddy }}"