- name: Ensure discord-sb folder exists
  file:
    path: "{{ DOCKER.host_path }}/discord-sb/"
    recurse: yes
    state: directory

- name: Ensure db.json exists
  file:
    path: "{{ DOCKER.host_path }}/discord-sb/db.json"
    state: touch

- name: Copy config.js file
  template:
    src: "config.j2"
    dest: "{{ DOCKER.host_path }}/discord-sb/config.json"

- name: Start Discord sound board
  community.docker.docker_container:
    name: discord-sb
    image: abeltramo/discord-soundbot
    pull: true
    state: started
    recreate: no
    restart_policy: always
    network_mode: "{{ DOCKER.net.traefik }}"
    purge_networks: no
    container_default_behavior: "compatibility"
    volumes:
      - "{{ DOCKER.host_path }}/discord-sb/sounds:/app/sounds"
      - "{{ DOCKER.host_path }}/discord-sb/db.json:/app/db.json"
      - "{{ DOCKER.host_path }}/discord-sb/config.json:/app/config/config.json"
