- docker_volume:
    name: theia-project
    state: present
    force: no

- name: "Start Theia"
  community.docker.docker_container:
    name: theia
    image: theiaide/theia-full
    pull: true
    state: started
    recreate: yes
    restart_policy: on-failure
    restart_retries: 1
    env:
      ACME_AGREE: "true"
    volumes:
      - theia-project:/home/project:cached
    networks:
      - name: "{{ DOCKER.net.traefik }}"
    purge_networks: yes