- community.docker.docker_container:
    name: jackett
    image: linuxserver/jackett
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "{{ DOCKER.host_path }}/jackett/config:/config"
    labels:
      traefik.frontend.rule: "Host: {{ traefik.url }}"
      traefik.port: "9117"
      traefik.enable: "true"
    env:
      TZ: "Europe/London"
    purge_networks: yes
    networks:
      - name: "{{ DOCKER.net.traefik }}"