- name: Gather package facts
  package_facts:
    manager: apt
  when: "ansible_facts.packages is not defined"

- name: Install docker
  include_role:
    name: docker
    tasks_from: debian-install
  when: '"docker-ce" not in ansible_facts.packages'

- name: "Start docker service if stopped"
  service:
    name: docker
    state: started
#  when:  molecule is not defined # TODO: doesn't work on molecule