- name: Gather package facts
  package_facts:
    manager: apt

- name: "Install Docker dependencies"
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg2, software-properties-common]
    update_cache: yes
  when: '"docker-ce" not in ansible_facts.packages'

- name: "Add Docker's public PGP key to the APT keyring"
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
  when: '"docker-ce" not in ansible_facts.packages'

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  when: '"docker-ce" not in ansible_facts.packages'

- name: "Configure Docker's upstream APT repository"
  apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: true
  when: '"docker-ce" not in ansible_facts.packages'

- name: "Install Docker"
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    update_cache: yes
  when: '"docker-ce" not in ansible_facts.packages'

- name: "Install python-pip"
  apt:
    name: [python3-pip]

- name: "Install docker-py (used by Ansible to run remote docker)"
  pip:
    name: [virtualenv, setuptools, docker, docker-compose]

- name: "Create {{ DOCKER.host_path }} folder"
  file:
    path: "{{ DOCKER.host_path }}"
    state: directory
  become: yes