##########

- name: Gather package facts
  package_facts:
    manager: apt
  when: ansible_facts.packages is not defined

- name: "Install PHP if missing"
  import_tasks: "php-install.yml"
  when: '"php7.4-fpm" not in ansible_facts.packages'

- name: "Ensure PHP is up and running"
  service:
    name: php7.4-fpm
    state: started

- name: "PHP Performance Tuning"
  import_tasks: "php-tuning.yml"
  when: tune_php

- name: "Ensure Nextcloud folder exists"
  file:
    path: /var/www
    recurse: yes
    state: directory

- name: "Check /var/www/nextcloud folder exists"
  stat:
    path: /var/www/nextcloud
  register: nextcloud_www_folder

- name: "Download and unzip Nextcloud {{ nextcloud_version }}"
  unarchive:
    src: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: /var/www
    owner: "www-data"
    group: "www-data"
    remote_src: yes
  when: not nextcloud_www_folder.stat.exists

- name: Create Nextcloud configuration
  template:
    owner: "www-data"
    group: "www-data"
    src: "nextcloud.config.j2"
    dest: "/var/www/nextcloud/config/nextcloud.config.php"

- name: Nextcloud cron service
  cron:
    name: "nextcloud cron"
    minute: "*/5"
    job: "php -f /var/www/nextcloud/cron.php"
    user: "www-data"

- name: "CRON: cleanup php sessions, fixes: https://github.com/nextcloud/server/issues/7628"
  cron:
    name: "cleanup php sessions"
    minute: "*/30"
    job: "[ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi"
    user: "root"

- name: "Install NGINX if missing"
  import_tasks: "nginx.yml"
  when: '"nginx" not in ansible_facts.packages'