- name: "Gather facts"
  gather_facts:
  when: 'ansible_distribution_release is not defined'

- name: "Install basic GPG packages"
  apt:
    name:
      - gnupg2
    update_cache: yes

- name: Import Sury GPG signing key [Debian/Ubuntu]
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    id: 15058500A0235D97F5D10063B188E2B695BD4743
    state: present

- name: Add Sury repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present

- name: "Update repositories and install packages"
  apt:
    name:
      - curl
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-gmp"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-redis"
      - "php{{ php_version }}-bz2"
#      - "php{{ php_version }}-json " # Removed as a module from 8.0
      - "php{{ php_version }}-imagick"
      - "php{{ php_version }}-apcu"
      - imagemagick
      - imagemagick-common
      - ffmpeg
      - unzip
    update_cache: yes