# PHP Tuning
# See: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

- name: PHP Tuning
  block:
    - name: PHP Tuning - Ensure clear_env = no
      lineinfile:
        path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
        regexp: '^clear_env'
        line: clear_env = no

    - name: PHP ini tuning
      community.general.ini_file:
        section: null
        path: "/etc/php/{{ php_version }}/mods-available/apcu.ini"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        backup: no
        state: present
      with_items:
        - { option: "max_execution_time", value: "3600" }
        - { option: "max_input_time", value: "3600" }
        - { option: "session.gc_divisor", value: "1000" }
        - { option: "session.gc_maxlifetime", value: "1440" }
        - { option: "session.gc_probability", value: "1" }
        - { option: "post_max_size", value: "1024M" }
        - { option: "upload_max_filesize", value: "1024M" }
        - { option: "memory_limit", value: "1024M" }
        - { option: "output_buffering", value: "0" }

    # See: https://github.com/nextcloud/server/issues/27781
    - name: APCU Fix
      community.general.ini_file:
        section: null
        path: "/etc/php/{{ php_version }}/mods-available/apcu.ini"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        backup: no
        state: present
      with_items:
        - { option: "apc.enable_cli", value: "1" }
        - { option: "apc.shm_size", value: "64M" }

    - name: OPCache
      community.general.ini_file:
        path: "/etc/php/{{ php_version }}/fpm/php.ini"
        section: opcache
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        backup: no
        state: present
      with_items: # Taken from https://www.scalingphpbook.com/blog/2014/02/14/best-zend-opcache-settings.html
        - { option: "opcache.enable", value: "1" }
        - { option: "opcache.revalidate_freq", value: "0" }
        - { option: "opcache.validate_timestamps", value: "0" }
        - { option: "opcache.max_accelerated_files", value: "10000" }
        - { option: "opcache.memory_consumption", value: "192" }
        - { option: "opcache.interned_strings_buffer", value: "16" }
        - { option: "opcache.fast_shutdown", value: "1" }

- name: "Restart php-fpm"
  service:
    name: "{{ php_package }}"
    state: restarted