- name: is Traefik running?
  community.docker.docker_container_info:
    name: traefik-local
  register: traefik_container

- name: Install Traefik
  include_role:
    name: traefik
    tasks_from: docker-start
  when: 'not traefik_container.exists'
