- name: "Set fs.inotify.max_user_watches=262144 in /etc/sysctl.conf"
  sysctl:
    name: fs.inotify.max_user_watches
    value: '262144'
    state: present
    reload: yes

# ONLY ENABLE IF YOU HAVE ENOUGH RAM AVAILABLE
#
#- name: Create ramdisk for transcoding
#  include_role:
#    name: ramdisk
#  vars:
#    ramdisk_path: "{{ transcoding_folder }}"
#    ramdisk_size: "8G"

- name: Create transcode directory
  file:
    path: "{{ transcoding_folder }}/transcode"
    state: directory
    mode: '0755'
  become: no

- name: Create cache directory
  file:
    path: "{{ transcoding_folder }}/cache"
    state: directory
    mode: '0755'
  become: no

- community.docker.docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env:
      TZ: 'Europe/London'
      PLEX_CLAIM: "{{ claim }}"
      ADVERTISE_IP: "{{ traefik.url }}"
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
    volumes:
      - "{{ DOCKER.host_path }}/plex/config:/config"
      - "{{ transcoding_folder }}/transcode:/transcode"
      - "{{ transcoding_folder }}/cache:/config/Library/Application Support/Plex Media Server/Cache/Transcode"
      - "{{ data_folder }}:/data:ro"
    devices:
      - /dev/dri:/dev/dri
#    privileged: true
    labels:
      traefik.frontend.rule: "Host: {{ traefik.url }}"
      traefik.port: "32400"
      traefik.enable: "true"
    networks:
      - name: "{{ DOCKER.net.traefik }}"
    purge_networks: yes