- name: "apt install Neovim"
  become: yes
  apt:
    name: [neovim]
    update_cache: yes

- name: "create vim-plug folder"
  become: no
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory

- name: "install vim-plug"
  become: no
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: "create nvim config folder"
  become: no
  ansible.builtin.file:
    path: ~/.config/nvim/
    state: directory

- name: "copy neovim config file"
  become: no
  ansible.builtin.copy:
    src: init.vim
    dest: ~/.config/nvim/init.vim

- name: "install plugins"
  become: no
  command: 'nvim -es -u .config/nvim/init.vim -i NONE -c "PlugInstall" -c "qa"'

