- name: "Start alltube"
  community.docker.docker_container:
    name: ytdl-webserver
    image: algram/ytdl-webserver
    pull: true
    state: started
    recreate: yes
    restart_policy: on-failure
    restart_retries: 2
    env:
      TZ: 'Europe/London'
      PGID: "0"
      PUID: "0"
    volumes:
      - /mnt/data/youtube-dl:/home/app/public/temp
    networks:
      - name: "{{ DOCKER.net.traefik }}"
    purge_networks: yes
    labels:
      traefik.frontend.rule: "Host: {{ traefik.url }}"
      traefik.port: "3000"
      traefik.enable: "true"